- name: Development libraries
  apt: name={{item}} state=installed
  with_items:
    - build-essential
    - git

    - python-dev
    - python-virtualenv
    - python-setuptools
    - ipython

    - libjpeg-dev
    - libtiff-dev
    - libfreetype6-dev
    - libpq-dev

    - libbz2-dev
    - libxml2-dev
    - libxslt1-dev
    - libxslt-dev
    - lib32z1
    - lib32z1-dev
    - lib32ncurses5
    - libbz2-1.0:i386
    - libc6:i386
    - libstdc++6:i386

    - fonts-firacode

    - zopfli
    - optipng

  become: yes

- import_tasks: pyenv.yaml
  tags: [python]

- import_tasks: ruby.yaml
  tags: [ruby]

- import_tasks: node.yaml
  tags: [node]

- import_tasks: vscode.yaml
  tags: [editor]

- import_tasks: postman.yaml
