#- name: Gravit-designer (snap package)
#  shell:  snap install gravit-designer
#  become: True

- name: Design tool packages
  apt: name={{item}} state=installed
  with_items:
    - gimp
    - inkscape
  become: yes
