- name: Development libraries
  apt:
    name: ""
  with_items:
    - libc6:i386
    - libncurses5:i386
    - libstdc++6:i386
    - lib32z1
    - libbz2-1.0:i386
    - build-essential
    - libjpeg-dev
    - libtiff-dev
    - libfreetype6-dev
    - git
    - libpq-dev
    - python-dev
    - python-virtualenv
    - python-setuptools
    - ipython
    - libbz2-dev
    - libxml2-dev
    - libxslt1-dev
    - libxslt-dev
    - lib32z1-dev

    - zopfli
    - optipng

  become: yes
