- import_tasks: systools.yaml
- import_tasks: devtools.yaml
- import_tasks: nopasssudo.yaml
- import_tasks: chrome.yaml
- import_tasks: sublime.yaml
- import_tasks: slack.yaml
  tags: [chat]
- import_tasks: networking.yaml
- import_tasks: bin/main.yaml
- import_tasks: design.yaml
  tags: [multimedia, design]
- import_tasks: audio.yaml
  tags: [multimedia audio]
- import_tasks: mongodb.yaml
  tags: [db]
