- name: Install GPG key for SublimeText
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: true

- name: Add repositories into sources list
  apt_repository:
    repo: deb {{ item.repo }} {{ item.add }}
    state: present
    filename: "{{ item.file }}"
  with_items:
    - repo: https://download.sublimetext.com/
      add: apt/stable/
      file: sublime
  become: true

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - sublime-text
  become: true
